{% set version = "0.100.0" %}  
{% set sha256 = "00b94984d3140e286e06d4beca2926ef80e0a0cc3ada75916e4fb9fa66ec28ad" %}

package:
  name: nushell
  version: {{ version }}

source:
  url: https://github.com/nushell/nushell/archive/refs/tags/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  #script: cargo build --release && cargo install --locked --path .
  #script: cargo install --locked --path . --root={{ PREFIX }}
  #script_env:
  #  - CARGO_HOME={{ PREFIX }}

requirements:
  build:
    # Default version in CBC.yaml is 1.82.0 we need >=1.66.1
    # see: https://www.nushell.sh/book/installation.html#installing-rust
    - {{ compiler('rust') }}
    - {{ compiler('c') }}

test:
  commands:
    - nu -h

about:
  home: https://github.com/nushell
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "A library for reading, writing, and processing SEG-Y seismic data."
  description: |
    take the Unix philosophy of shells, where pipes connect simple commands 
    together, and bring it to the modern style of development. Thus, rather 
    than being either a shell, or a programming language, Nushell connects 
    both by bringing a rich programming language and a full-featured shell 
    together into one package.
  dev_url: https://github.com/nushell
  doc_url: https://www.nushell.sh/

extra:
  services:
    recipe-maintainers:
       - bkreider
    comment: Built for internal use.

